SET check_function_bodies = false;
INSERT INTO public.play_styles (value, comment) VALUES ('SP', 'SINGLE PLAY');
INSERT INTO public.play_styles (value, comment) VALUES ('DP', 'DOUBLE PLAY');
INSERT INTO public.track_types (value, comment) VALUES ('BEGINNER', NULL);
INSERT INTO public.track_types (value, comment) VALUES ('NORMAL', NULL);
INSERT INTO public.track_types (value, comment) VALUES ('HYPER', NULL);
INSERT INTO public.track_types (value, comment) VALUES ('ANOTHER', NULL);
INSERT INTO public.track_types (value, comment) VALUES ('LEGGENDARIA', NULL);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('1', '1st style', '1st', 0);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('s', 'substream', 'sub', 1);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('2', '2nd style', '2nd', 2);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('3', '3rd style', '3rd', 3);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('4', '4th style', '4th', 4);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('5', '5th style', '5th', 5);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('6', '6th style', '6th', 6);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('7', '7th style', '7th', 7);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('8', '8th style', '8th', 8);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('9', '9th style', '9th', 9);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('10', '10th style', '10th', 10);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('11', 'IIDX RED', 'RED', 11);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('12', 'HAPPY SKY', 'HS', 12);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('13', 'DistorteD', 'DD', 13);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('14', 'GOLD', 'GOLD', 14);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('15', 'DJ TROOPERS', 'DJT', 15);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('16', 'EMPRESS', 'EMP', 16);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('17', 'SIRIUS', 'SIR', 17);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('18', 'Resort Anthem', 'RA', 18);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('19', 'Lincle', 'Lin', 19);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('20', 'tricoro', 'tri', 20);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('21', 'SPADA', 'SPD', 21);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('22', 'PENDUAL', 'PEN', 22);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('23', 'copula', 'cop', 23);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('24', 'SINOBUZ', 'SINO', 24);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('25', 'CANNON BALLERS', 'CB', 25);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('26', 'Rootage', 'Root', 26);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('27', 'HEROIC VERSE', 'HV', 27);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('28', 'BISTROVER', 'BIS', 28);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('29', 'CastHour', 'CH', 29);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('30', 'RESIDENT', 'RES', 30);
INSERT INTO public.versions (id, name, short_name, display_order) VALUES ('31', 'EPOLIS', 'EPO', 31);
